<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\SuccessStory;
use Illuminate\Database\Seeder;

class SuccessStorySeeder extends Seeder
{
    /**
     * Seed 22 authentic Pakistani tech career transition journeys.
     */
    public function run(): void
    {
        $studentUser = User::where('role', 'student')->first() ?? User::first();
        $userId = $studentUser?->id;

        // Clear existing legacy seed stories to prevent western / duplicate name carryover
        SuccessStory::whereIn('title', [
            'Elena Rostova — From QA to Production AI Engineer',
            'Marcus Vance — Support Tech to AWS Cloud Solutions Architect',
            'Amina Al-Mansoor — Self-Taught to Full-Stack Engineer at Stripe',
        ])->delete();

        $pakistaniStories = [
            [
                'title' => 'Muhammad Ali — Self-Taught to Senior Full-Stack Engineer at Systems Ltd',
                'domain' => 'Software Engineering',
                'educational_path' => 'Self-Taught & Aptech Karachi Diploma in Software Engineering',
                'challenges' => 'Transitioning from a non-CS commerce background to enterprise PHP/Laravel and React architecture without a traditional 4-year degree.',
                'timeline_path' => 'Aptech Diploma (2022) → Full-Stack Track on PathSeeker → Junior Dev at Karachi Software House → Senior Full-Stack Engineer at Systems Ltd (2026)',
                'outcome' => 'Promoted to Senior Full-Stack Engineer at Systems Ltd, architecting enterprise microservices and fintech portals with a 180% salary leap.',
                'story_text' => 'PathSeeker\'s structured full-stack blueprint provided the exact industry-grade system design patterns I needed. Coming from Aptech Karachi with zero formal CS degree, it gave me the roadmap to crack the Systems Ltd technical evaluation and lead high-scale enterprise deliveries.',
                'image_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Ayesha Siddiqui — FAST-NUCES Graduate to AI Research Engineer at Arbisoft',
                'domain' => 'Artificial Intelligence & Data',
                'educational_path' => 'B.S. Computer Science, FAST-NUCES Lahore (Batch of 2023)',
                'challenges' => 'Bridging the gap between academic machine learning theory and production LLM fine-tuning, latency optimization, and vector search inference.',
                'timeline_path' => 'FAST Undergraduate (2023) → PathSeeker AI Blueprint → Open-Source LLM Contributor → AI Engineer at Arbisoft Lahore (2026)',
                'outcome' => 'Landed Machine Learning & LLM deployment role at Arbisoft, designing autonomous vector pipelines and multi-modal models for US enterprises.',
                'story_text' => 'The mathematical breakdown and vector DB cheat sheets in PathSeeker bridged the gap between academic theory at FAST and production MLOps. Within 7 months of following the AI track, I was building production GenAI agents for international clients at Arbisoft.',
                'image_url' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Bilal Ahmed — NED Mechanical Graduate to Cloud DevOps Lead at 10Pearls',
                'domain' => 'Cloud & Infrastructure',
                'educational_path' => 'B.E. Mechanical Engineering, NED University of Engineering & Technology Karachi',
                'challenges' => 'Shifting from mechanical CAD tooling to Linux kernel internals, Docker containerization, and multi-region Kubernetes topologies.',
                'timeline_path' => 'Mechanical Grad (2023) → PathSeeker DevOps Track → AWS Solutions Architect Associate → Cloud Lead at 10Pearls (2026)',
                'outcome' => 'Orchestrating high-availability microservices across AWS and GCP for tier-1 North American enterprise clients.',
                'story_text' => 'PathSeeker gave me a rock-solid step-by-step path to master Terraform, Docker, and Kubernetes within 8 months after completing my mechanical degree at NED. The interactive terminal guides and cloud cheat sheets made the transition seamless.',
                'image_url' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Zainab Khan — NUST Islamabad Alum to Senior UI/UX Product Designer at Careem',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Software Engineering, NUST SEECS Islamabad',
                'challenges' => 'Balancing technical coding with human-centered product ergonomics, interactive prototyping, and scalable Figma design systems.',
                'timeline_path' => 'NUST Alum (2023) → Design System Blueprint on PathSeeker → UX Freelancer → Product Designer at Careem (2026)',
                'outcome' => 'Designing ride-hailing and fintech consumer interfaces serving millions of active users across MENA and Pakistan.',
                'story_text' => 'The interaction design principles and WCAG accessibility standards on PathSeeker elevated my portfolio from student prototypes to tier-1 enterprise design. It gave me the competitive edge to join Careem\'s core product design team.',
                'image_url' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Usman Tariq — COMSATS Lahore to Remote Distributed Systems Engineer (US Fintech)',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Computer Science, COMSATS University Islamabad (Lahore Campus)',
                'challenges' => 'Cracking remote US tech screens on distributed event queues, Go (Golang) concurrency, and low-latency Kafka streaming.',
                'timeline_path' => 'Junior Backend Dev (2023) → Distributed Systems Blueprint → Open-Source Builder → US Remote Backend Engineer ($85k/yr) (2026)',
                'outcome' => 'Secured a six-figure remote engineering contract handling high-frequency transaction settlement and ledger consistency.',
                'story_text' => 'PathSeeker\'s distributed systems roadmaps and Go interview simulations helped me outcompete international applicants during remote hiring. Working remotely from Lahore for a Silicon Valley fintech has been life-changing.',
                'image_url' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Hira Riaz — SSUET Karachi to Cyber Threat Analyst at Trillium Information Security',
                'domain' => 'Cybersecurity',
                'educational_path' => 'B.S. Computer Engineering, Sir Syed University of Engineering & Technology (SSUET)',
                'challenges' => 'Mastering SIEM log correlation, network forensics, packet capture analysis, and passing CEH / Security+ certifications.',
                'timeline_path' => 'Network Intern (2023) → SOC Analyst Blueprint on PathSeeker → Threat Hunter → SOC Tier-2 Lead (2026)',
                'outcome' => 'Protecting banking and telecom infrastructure across Pakistan against advanced persistent threats (APTs) and ransomware.',
                'story_text' => 'The cybersecurity laboratory roadmaps and threat modeling scenarios on PathSeeker gave me real-world SOC experience before I even set foot in an interview room. I knew exactly how to investigate malicious telemetry from day one.',
                'image_url' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Hamza Farooq — UET Lahore to Mobile Application Lead at VentureDive',
                'domain' => 'Mobile Development',
                'educational_path' => 'B.S. Computer Science, UET Lahore',
                'challenges' => 'Migrating legacy mobile architectures to declarative Flutter and Kotlin Multiplatform ecosystems with offline synchronization.',
                'timeline_path' => 'Android Developer (2023) → Flutter Track on PathSeeker → Mobile Architect → Lead Mobile Dev at VentureDive (2026)',
                'outcome' => 'Spearheading healthcare and logistics mobile applications with over 2 million active installs across the GCC region.',
                'story_text' => 'PathSeeker’s architectural blueprints for Flutter state management and offline synchronization made all the difference in scaling our mobile stack at VentureDive. The codebase best practices directly influenced our flagship releases.',
                'image_url' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Fatima Noor — IBA Karachi Graduate to Senior Data Scientist at Afiniti',
                'domain' => 'Data Science',
                'educational_path' => 'B.S. Computer Science & Mathematics, IBA Karachi',
                'challenges' => 'Applying complex Bayesian inference and predictive statistical modeling to real-time call center telemetry.',
                'timeline_path' => 'Business Analyst (2023) → Data Science Mastery on PathSeeker → Predictive Modeler → Senior Data Scientist at Afiniti (2026)',
                'outcome' => 'Developing behavioral matching algorithms generating multi-million dollar client value across multinational telecommunications networks.',
                'story_text' => 'IBA gave me the theoretical math, but PathSeeker gave me the BigQuery, PyTorch, and scalable pipeline engineering to thrive at Afiniti. It transformed how I approach machine learning problem-solving.',
                'image_url' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Daniyal Malik — GIKI Graduate to Autonomous AI Agent Architect at Tkxel',
                'domain' => 'Artificial Intelligence & Data',
                'educational_path' => 'B.S. Computer Engineering, GIK Institute (GIKI) Topi',
                'challenges' => 'Integrating multi-modal reasoning models with real-time vector retrieval, memory persistence, and tool-calling execution.',
                'timeline_path' => 'Graduate Engineer (2024) → AI Agent Blueprint on PathSeeker → GenAI Specialist → Principal Agent Architect at Tkxel (2026)',
                'outcome' => 'Deployed enterprise autonomous agent swarms that automate automated software testing and financial regulatory compliance.',
                'story_text' => 'PathSeeker’s GenAI contextual architecture module is the most up-to-date guide available in Pakistan. It directly landed me my AI architect role at Tkxel and helped us ship autonomous agent solutions globally.',
                'image_url' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Maham Tariq — PUCIT Lahore to Lead Front-End Engineer at Dubizzle Labs (EMPG)',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Software Engineering, Punjab University College of Information Technology (PUCIT)',
                'challenges' => 'Optimizing Largest Contentful Paint (LCP) and micro-frontend state synchronization across heavy property portals.',
                'timeline_path' => 'React Junior (2023) → Next.js & Web Performance Blueprint → Senior Frontend Dev → Tech Lead at Dubizzle Labs (2026)',
                'outcome' => 'Managing high-traffic frontend web infrastructure serving 10M+ monthly property and automotive searches in Pakistan and UAE.',
                'story_text' => 'PathSeeker taught me web performance at the browser rendering engine level. My Core Web Vitals audit and SSR optimization directly led to my promotion to Tech Lead at Dubizzle Labs.',
                'image_url' => 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Saad Qureshi — UBIT Karachi to Cloud Security Lead at Confiz',
                'domain' => 'Cloud & Infrastructure',
                'educational_path' => 'B.S. Computer Science, UBIT University of Karachi',
                'challenges' => 'Implementing zero-trust architectures, IAM least privilege policies, and SOC 2 Type II compliance in hybrid enterprise environments.',
                'timeline_path' => 'Support Engineer (2023) → Cloud Security Track → Multi-Cloud Certified → Cloud Security Lead at Confiz (2026)',
                'outcome' => 'Directing security postures and automated vulnerability remediations across 40+ Azure and AWS customer production tenancies.',
                'story_text' => 'PathSeeker’s IAM and cloud security blueprints turned complex compliance frameworks into easy-to-follow actionable projects. It prepared me to lead security audits for major US enterprise clients.',
                'image_url' => 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Sana Javed — ITU Lahore Graduate to Data Platform Engineer at S&P Global Pakistan',
                'domain' => 'Data Science',
                'educational_path' => 'B.S. Computer Science, Information Technology University (ITU) Lahore',
                'challenges' => 'Building petabyte-scale Apache Spark streaming pipelines with Apache Iceberg, dbt, and Kafka connectors.',
                'timeline_path' => 'ITU Graduate (2023) → Big Data Lakehouse Track on PathSeeker → Data Engineer at S&P Global (2026)',
                'outcome' => 'Optimizing global financial market telemetry pipelines processing billions of structured data points daily.',
                'story_text' => 'The lakehouse architecture diagrams and dbt / Spark guides in PathSeeker are unmatched in clarity. It was crucial for my S&P Global technical interviews and daily platform architecture.',
                'image_url' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Omair Hashmi — FAST Islamabad to Blockchain Protocol Engineer (Dubai Remote)',
                'domain' => 'Blockchain',
                'educational_path' => 'B.S. Computer Science, FAST-NUCES Islamabad',
                'challenges' => 'Writing gas-optimized Solidity smart contracts, implementing zero-knowledge proofs, and passing formal verification auditing.',
                'timeline_path' => 'Backend Dev (2023) → Web3 & Smart Contract Track → DeFi Protocol Builder → Web3 Lead for Dubai Client ($95k/yr) (2026)',
                'outcome' => 'Audited and deployed smart contracts managing over $40M in decentralized total value locked (TVL).',
                'story_text' => 'PathSeeker gave me the exact roadmap for EVM internals, assembly optimization, and security audits that enabled me to work internationally from Islamabad for high-growth Web3 foundations.',
                'image_url' => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Mariam Khalid — Kinnaird College to Product Growth & UX Researcher at Bazaar App',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Computer Science, Kinnaird College for Women Lahore',
                'challenges' => 'Conducting user research and interaction flows for non-tech-savvy merchant personas across retail supply chains in Pakistan.',
                'timeline_path' => 'Junior Designer (2023) → Product Strategy Blueprint on PathSeeker → UX Researcher at Bazaar (2026)',
                'outcome' => 'Redesigned onboarding workflows leading to a 34% increase in merchant weekly order completion and retention.',
                'story_text' => 'PathSeeker helped me connect design psychology with real commercial conversion metrics for local Pakistani B2B apps. It made my portfolio shine when applying to Bazaar.',
                'image_url' => 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Taha Siddiqui — NED Karachi to Senior SRE at Motive (KeepTruckin)',
                'domain' => 'Cloud & Infrastructure',
                'educational_path' => 'B.E. Computer Systems Engineering, NED University Karachi',
                'challenges' => 'Managing zero-downtime database failovers, Prometheus alerting, and distributed telemetry for millions of connected IoT fleet devices.',
                'timeline_path' => 'Linux Admin (2023) → SRE & Chaos Engineering Track → SRE at Motive Pakistan (2026)',
                'outcome' => 'Maintaining 99.99% system availability across critical North American freight tracking and dispatch routing infrastructure.',
                'story_text' => 'The Chaos Engineering and OpenTelemetry cheat sheets on PathSeeker prepared me for the high-stakes SRE interview loop at Motive. The system observability exercises gave me immediate credibility.',
                'image_url' => 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Rabia Aslam — NUST Islamabad to NLP & Conversational AI Specialist at Krave Mart',
                'domain' => 'Artificial Intelligence & Data',
                'educational_path' => 'M.S. Data Science, NUST Islamabad',
                'challenges' => 'Fine-tuning Roman Urdu multilingual tokenizers and customer intent classification models for quick-commerce delivery apps.',
                'timeline_path' => 'Data Analyst (2023) → LLM Fine-Tuning Track → NLP Specialist at Krave Mart (2026)',
                'outcome' => 'Automated 65% of customer support chat inquiries with real-time Roman Urdu understanding and sentiment routing models.',
                'story_text' => 'PathSeeker’s tokenization and LoRA fine-tuning guides gave me the practical tools to build local language models with extreme precision. It has transformed customer experience at Krave Mart.',
                'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Zeeshan Butt — UET Taxila to Penetration Tester & Red Teamer at Rewterz',
                'domain' => 'Cybersecurity',
                'educational_path' => 'B.S. Software Engineering, UET Taxila',
                'challenges' => 'Weaponizing custom exploits, bypassing modern EDR defenses, and securing core banking APIs against vulnerability exploits.',
                'timeline_path' => 'Security Enthusiast (2023) → Ethical Hacking Blueprint → OSCP Certified → Senior Security Consultant at Rewterz (2026)',
                'outcome' => 'Successfully identified 35+ critical zero-day vulnerabilities in enterprise core banking and payment gateway systems.',
                'story_text' => 'PathSeeker\'s offensive security roadmaps provided the structured lab exercises I needed to pass OSCP on my first attempt and join Rewterz\'s elite red team.',
                'image_url' => 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Nimra Sheikh — IBA Karachi to Lead Product Manager (Tech) at Dastgyr',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Computer Science, IBA Karachi',
                'challenges' => 'Translating complex logistics routing algorithms and inventory ERPs into actionable agile engineering sprints.',
                'timeline_path' => 'Associate PM (2023) → Technical Architecture for Leaders on PathSeeker → Lead PM at Dastgyr (2026)',
                'outcome' => 'Spearheaded nationwide B2B fintech and supply chain products facilitating over Rs 2 Billion in digital transactions.',
                'story_text' => 'PathSeeker helped me communicate seamlessly with senior backend architects and design resilient technical product roadmaps for the Pakistani market.',
                'image_url' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Arsalan Baig — FAST Lahore to Game Engine Developer at Mindstorm Studios',
                'domain' => 'Software Engineering',
                'educational_path' => 'B.S. Computer Science, FAST-NUCES Lahore',
                'challenges' => 'Mastering C++ memory layouts, custom Vulkan shaders, and real-time multiplayer physics synchronization.',
                'timeline_path' => 'C++ Hobbyist (2023) → Game Architecture Blueprint on PathSeeker → Engine Programmer at Mindstorm (2026)',
                'outcome' => 'Developed physics simulation cores and shader passes for mobile and PC games downloaded by 20M+ users globally.',
                'story_text' => 'The low-level systems programming and memory optimization guides on PathSeeker gave me the exact edge needed for AAA game engine development in Lahore.',
                'image_url' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Anum Rehman — NED Karachi to Mobile Flutter Architect at Sadapay',
                'domain' => 'Mobile Development',
                'educational_path' => 'B.S. Computer Science, NED University Karachi',
                'challenges' => 'Engineering PCI-DSS compliant fintech mobile apps with biometric authentication, secure enclaves, and zero cryptographic leakage.',
                'timeline_path' => 'Junior Mobile Dev (2023) → Mobile Security & Architecture Track → Lead Mobile Dev at Sadapay (2026)',
                'outcome' => 'Engineered ultra-fast, biometric-authenticated banking app flows handling millions of peer-to-peer Mastercard transactions.',
                'story_text' => 'PathSeeker’s deep dive into mobile cryptographic storage, biometric authentication, and clean architecture made our fintech application rock-solid.',
                'image_url' => 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Shahzaib Hassan — GIKI Topi to DevOps Automation Specialist at Jazz (VEON)',
                'domain' => 'Cloud & Infrastructure',
                'educational_path' => 'B.S. Computer Engineering, GIKI Topi',
                'challenges' => 'Orchestrating automated telco-grade CI/CD pipelines across 50,000 microservice instances with zero downtime.',
                'timeline_path' => 'Systems Intern (2023) → Multi-Cloud Kubernetes Blueprint → Senior DevOps Engineer at Jazz (2026)',
                'outcome' => 'Reduced telco microservice deployment rollback rates by 92% with automated GitOps canary releases.',
                'story_text' => 'PathSeeker’s GitOps and ArgoCD real-world architectures were instrumental in modernizing our cloud-native deployment pipelines at Jazz.',
                'image_url' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
            [
                'title' => 'Kiran Fatima — FAST Karachi to Senior Data Analyst at Foodpanda Pakistan',
                'domain' => 'Data Science',
                'educational_path' => 'B.S. Computer Science, FAST-NUCES Karachi',
                'challenges' => 'Processing millions of geospatial delivery coordinates and calculating dynamic rider dispatch optimization curves.',
                'timeline_path' => 'Junior Analyst (2023) → Geospatial Data & SQL Blueprint on PathSeeker → Senior BI Analyst at Foodpanda (2026)',
                'outcome' => 'Reduced average food delivery turnaround time by 4.2 minutes across Karachi and Lahore through real-time route analytics.',
                'story_text' => 'PathSeeker showed me how to turn millions of raw delivery logs into executive-ready automated decision dashboards in PowerBI and Python.',
                'image_url' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
                'submitted_by' => $userId,
                'user_id' => $userId,
                'status' => SuccessStory::STATUS_APPROVED,
                'reviewed_at' => now(),
            ],
        ];

        foreach ($pakistaniStories as $story) {
            SuccessStory::updateOrCreate(
                ['title' => $story['title']],
                $story
            );
        }
    }
}
